// src/services/pdfService.ts
import PDFDocument from "pdfkit";
import { Response } from "express";

interface MenuItem {
  day: string;
  dishes: string[];
  isDayOff: boolean;
}

interface WeeklyMenuInput {
  startDate: Date;
  endDate: Date;
  weeklyMenu: {
    day: string;
    dishes: string[];
    isDayOff: boolean;
  }[];
}

class PdfService {
  generateMenuPdf(menu: WeeklyMenuInput, res: Response): void {
    const doc = new PDFDocument();

    // Set response headers
    res.setHeader("Content-Type", "application/pdf");
    res.setHeader(
      "Content-Disposition",
      "attachment; filename=weekly-menu.pdf"
    );

    doc.pipe(res);

    // Add title
    doc
      .fontSize(20)
      .font("Helvetica-Bold")
      .text("Weekly Menu", { align: "center" });
    doc.moveDown();

    // Add date range
    doc
      .fontSize(12)
      .font("Helvetica")
      .text(
        `From: ${new Date(menu.startDate).toLocaleDateString()} To: ${new Date(
          menu.endDate
        ).toLocaleDateString()}`,
        { align: "center" }
      );
    doc.moveDown(1.5);

    // Add menu items
    menu.weeklyMenu.forEach((dayMenu) => {
      doc.fontSize(16).font("Helvetica-Bold").text(dayMenu.day);
      doc.moveDown(0.5);

      if (dayMenu.isDayOff) {
        doc.font("Helvetica").fontSize(12).text("Day Off"); // Use standard Helvetica
      } else {
        const mealTypes = ["Breakfast", "Lunch", "Dinner"];
        // Ensure dishes array exists and has the expected length
        const dishes = dayMenu.dishes || [];
        mealTypes.forEach((mealType, index) => {
          doc
            .font("Helvetica-Bold")
            .fontSize(10)
            .text(`${mealType}: `, { continued: true, indent: 10 })
            .font("Helvetica")
            .fontSize(10)
            .text(dishes[index] || "Not specified");
          doc.moveDown(0.3);
        });
      }
      doc.moveDown(1);
    });

    // Footer
    doc
      .fontSize(8)
      .font("Helvetica")
      .text("Generated by Menu Scheduler App", 0, doc.page.height - 40, {
        align: "center",
      });

    doc.end();
  }
}

export const pdfService = new PdfService();
